apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: external-dns
      containers:
      # External DNS - Azure DNS Provider
      # Creates A and CNAME records in Azure DNS
      - name: external-dns-azure
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
          - --source=service
          - --source=ingress
          - --provider=azure
          - --azure-resource-group=your-dns-rg  # UPDATE: Your DNS zone resource group
          - --azure-subscription-id=your-subscription-id  # UPDATE: Your subscription ID
          - --domain-filter=example.com  # UPDATE: Your domain
          - --txt-owner-id=external-dns-azure
          - --interval=1m
          - --log-level=info
        env:
          - name: AZURE_CLIENT_ID
            value: "your-managed-identity-client-id"  # UPDATE: Your managed identity client ID

      # External DNS - Webhook Provider
      # Routes Traffic Manager requests to the webhook
      - name: external-dns-webhook
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
          - --source=service
          - --source=ingress
          - --provider=webhook
          - --webhook-provider-url=http://localhost:8888
          - --domain-filter=example.com  # UPDATE: Your domain
          - --txt-owner-id=external-dns-webhook
          - --interval=1m
          - --log-level=info

      # Traffic Manager Webhook Provider
      # Manages Azure Traffic Manager profiles and endpoints
      - name: traffic-manager-webhook
        image: your-registry.azurecr.io/external-dns-traffic-manager-webhook:latest  # UPDATE: Your container registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          name: webhook
          protocol: TCP
        - containerPort: 8080
          name: health
          protocol: TCP
        env:
          - name: WEBHOOK_PORT
            value: "8888"
          - name: LOG_LEVEL
            value: "info"
          - name: AZURE_SUBSCRIPTION_ID
            value: "your-subscription-id"  # UPDATE: Your subscription ID
          - name: AZURE_TENANT_ID
            value: "your-tenant-id"  # UPDATE: Your tenant ID
          - name: AZURE_CLIENT_ID
            value: "your-managed-identity-client-id"  # UPDATE: Your managed identity client ID
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5
